<?php

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['iso' => 'AF','name' => 'Afghanistan','dialing_code' => '93'],
            ['iso' => 'AL','name' => 'Albania','dialing_code' => '355'],
            ['iso' => 'DZ','name' => 'Algeria','dialing_code' => '213'],
            ['iso' => 'AS','name' => 'American Samoa','dialing_code' => '1684'],
            ['iso' => 'AD','name' => 'Andorra','dialing_code' => '376'],
            ['iso' => 'AO','name' => 'Angola','dialing_code' => '244'],
            ['iso' => 'AI','name' => 'Anguilla','dialing_code' => '1264'],
            ['iso' => 'AQ','name' => 'Antarctica','dialing_code' => '0'],
            ['iso' => 'AG','name' => 'Antigua and Barbuda','dialing_code' => '1268'],
            ['iso' => 'AR','name' => 'Argentina','dialing_code' => '54'],
            ['iso' => 'AM','name' => 'Armenia','dialing_code' => '374'],
            ['iso' => 'AW','name' => 'Aruba','dialing_code' => '297'],
            ['iso' => 'AU','name' => 'Australia','dialing_code' => '61'],
            ['iso' => 'AT','name' => 'Austria','dialing_code' => '43'],
            ['iso' => 'AZ','name' => 'Azerbaijan','dialing_code' => '994'],
            ['iso' => 'BS','name' => 'Bahamas','dialing_code' => '1242'],
            ['iso' => 'BH','name' => 'Bahrain','dialing_code' => '973'],
            ['iso' => 'BD','name' => 'Bangladesh','dialing_code' => '880'],
            ['iso' => 'BB','name' => 'Barbados','dialing_code' => '1246'],
            ['iso' => 'BY','name' => 'Belarus','dialing_code' => '375'],
            ['iso' => 'BE','name' => 'Belgium','dialing_code' => '32'],
            ['iso' => 'BZ','name' => 'Belize','dialing_code' => '501'],
            ['iso' => 'BJ','name' => 'Benin','dialing_code' => '229'],
            ['iso' => 'BM','name' => 'Bermuda','dialing_code' => '1441'],
            ['iso' => 'BT','name' => 'Bhutan','dialing_code' => '975'],
            ['iso' => 'BO','name' => 'Bolivia','dialing_code' => '591'],
            ['iso' => 'BA','name' => 'Bosnia and Herzegovina','dialing_code' => '387'],
            ['iso' => 'BW','name' => 'Botswana','dialing_code' => '267'],
            ['iso' => 'BV','name' => 'Bouvet Island','dialing_code' => '0'],
            ['iso' => 'BR','name' => 'Brazil','dialing_code' => '55'],
            ['iso' => 'IO','name' => 'British Indian Ocean Territory','dialing_code' => '246'],
            ['iso' => 'BN','name' => 'Brunei Darussalam','dialing_code' => '673'],
            ['iso' => 'BG','name' => 'Bulgaria','dialing_code' => '359'],
            ['iso' => 'BF','name' => 'Burkina Faso','dialing_code' => '226'],
            ['iso' => 'BI','name' => 'Burundi','dialing_code' => '257'],
            ['iso' => 'KH','name' => 'Cambodia','dialing_code' => '855'],
            ['iso' => 'CM','name' => 'Cameroon','dialing_code' => '237'],
            ['iso' => 'CA','name' => 'Canada','dialing_code' => '1'],
            ['iso' => 'CV','name' => 'Cape Verde','dialing_code' => '238'],
            ['iso' => 'KY','name' => 'Cayman Islands','dialing_code' => '1345'],
            ['iso' => 'CF','name' => 'Central African Republic','dialing_code' => '236'],
            ['iso' => 'TD','name' => 'Chad','dialing_code' => '235'],
            ['iso' => 'CL','name' => 'Chile','dialing_code' => '56'],
            ['iso' => 'CN','name' => 'China','dialing_code' => '86'],
            ['iso' => 'CX','name' => 'Christmas Island','dialing_code' => '61'],
            ['iso' => 'CC','name' => 'Cocos (Keeling) Islands','dialing_code' => '672'],
            ['iso' => 'CO','name' => 'Colombia','dialing_code' => '57'],
            ['iso' => 'KM','name' => 'Comoros','dialing_code' => '269'],
            ['iso' => 'CG','name' => 'Congo','dialing_code' => '242'],
            ['iso' => 'CD','name' => 'Congo, the Democratic Republic of the','dialing_code' => '242'],
            ['iso' => 'CK','name' => 'Cook Islands','dialing_code' => '682'],
            ['iso' => 'CR','name' => 'Costa Rica','dialing_code' => '506'],
            ['iso' => 'CI','name' => 'Cote D\'Ivoire','dialing_code' => '225'],
            ['iso' => 'HR','name' => 'Croatia','dialing_code' => '385'],
            ['iso' => 'CU','name' => 'Cuba','dialing_code' => '53'],
            ['iso' => 'CY','name' => 'Cyprus','dialing_code' => '357'],
            ['iso' => 'CZ','name' => 'Czech Republic','dialing_code' => '420'],
            ['iso' => 'DK','name' => 'Denmark','dialing_code' => '45'],
            ['iso' => 'DJ','name' => 'Djibouti','dialing_code' => '253'],
            ['iso' => 'DM','name' => 'Dominica','dialing_code' => '1767'],
            ['iso' => 'DO','name' => 'Dominican Republic','dialing_code' => '1809'],
            ['iso' => 'EC','name' => 'Ecuador','dialing_code' => '593'],
            ['iso' => 'EG','name' => 'Egypt','dialing_code' => '20'],
            ['iso' => 'SV','name' => 'El Salvador','dialing_code' => '503'],
            ['iso' => 'GQ','name' => 'Equatorial Guinea','dialing_code' => '240'],
            ['iso' => 'ER','name' => 'Eritrea','dialing_code' => '291'],
            ['iso' => 'EE','name' => 'Estonia','dialing_code' => '372'],
            ['iso' => 'ET','name' => 'Ethiopia','dialing_code' => '251'],
            ['iso' => 'FK','name' => 'Falkland Islands (Malvinas)','dialing_code' => '500'],
            ['iso' => 'FO','name' => 'Faroe Islands','dialing_code' => '298'],
            ['iso' => 'FJ','name' => 'Fiji','dialing_code' => '679'],
            ['iso' => 'FI','name' => 'Finland','dialing_code' => '358'],
            ['iso' => 'FR','name' => 'France','dialing_code' => '33'],
            ['iso' => 'GF','name' => 'French Guiana','dialing_code' => '594'],
            ['iso' => 'PF','name' => 'French Polynesia','dialing_code' => '689'],
            ['iso' => 'TF','name' => 'French Southern Territories','dialing_code' => '0'],
            ['iso' => 'GA','name' => 'Gabon','dialing_code' => '241'],
            ['iso' => 'GM','name' => 'Gambia','dialing_code' => '220'],
            ['iso' => 'GE','name' => 'Georgia','dialing_code' => '995'],
            ['iso' => 'DE','name' => 'Germany','dialing_code' => '49'],
            ['iso' => 'GH','name' => 'Ghana','dialing_code' => '233'],
            ['iso' => 'GI','name' => 'Gibraltar','dialing_code' => '350'],
            ['iso' => 'GR','name' => 'Greece','dialing_code' => '30'],
            ['iso' => 'GL','name' => 'Greenland','dialing_code' => '299'],
            ['iso' => 'GD','name' => 'Grenada','dialing_code' => '1473'],
            ['iso' => 'GP','name' => 'Guadeloupe','dialing_code' => '590'],
            ['iso' => 'GU','name' => 'Guam','dialing_code' => '1671'],
            ['iso' => 'GT','name' => 'Guatemala','dialing_code' => '502'],
            ['iso' => 'GN','name' => 'Guinea','dialing_code' => '224'],
            ['iso' => 'GW','name' => 'Guinea-Bissau','dialing_code' => '245'],
            ['iso' => 'GY','name' => 'Guyana','dialing_code' => '592'],
            ['iso' => 'HT','name' => 'Haiti','dialing_code' => '509'],
            ['iso' => 'HM','name' => 'Heard Island and Mcdonald Islands','dialing_code' => '0'],
            ['iso' => 'VA','name' => 'Holy See (Vatican City State)','dialing_code' => '39'],
            ['iso' => 'HN','name' => 'Honduras','dialing_code' => '504'],
            ['iso' => 'HK','name' => 'Hong Kong','dialing_code' => '852'],
            ['iso' => 'HU','name' => 'Hungary','dialing_code' => '36'],
            ['iso' => 'IS','name' => 'Iceland','dialing_code' => '354'],
            ['iso' => 'IN','name' => 'India','dialing_code' => '91'],
            ['iso' => 'ID','name' => 'Indonesia','dialing_code' => '62'],
            ['iso' => 'IR','name' => 'Iran, Islamic Republic of','dialing_code' => '98'],
            ['iso' => 'IQ','name' => 'Iraq','dialing_code' => '964'],
            ['iso' => 'IE','name' => 'Ireland','dialing_code' => '353'],
            ['iso' => 'IL','name' => 'Israel','dialing_code' => '972'],
            ['iso' => 'IT','name' => 'Italy','dialing_code' => '39'],
            ['iso' => 'JM','name' => 'Jamaica','dialing_code' => '1876'],
            ['iso' => 'JP','name' => 'Japan','dialing_code' => '81'],
            ['iso' => 'JO','name' => 'Jordan','dialing_code' => '962'],
            ['iso' => 'KZ','name' => 'Kazakhstan','dialing_code' => '7'],
            ['iso' => 'KE','name' => 'Kenya','dialing_code' => '254'],
            ['iso' => 'KI','name' => 'Kiribati','dialing_code' => '686'],
            ['iso' => 'KP','name' => 'Korea, Democratic People\'s Republic of','dialing_code' => '850'],
            ['iso' => 'KR','name' => 'Korea, Republic of','dialing_code' => '82'],
            ['iso' => 'KW','name' => 'Kuwait','dialing_code' => '965'],
            ['iso' => 'KG','name' => 'Kyrgyzstan','dialing_code' => '996'],
            ['iso' => 'LA','name' => 'Lao People\'s Democratic Republic','dialing_code' => '856'],
            ['iso' => 'LV','name' => 'Latvia','dialing_code' => '371'],
            ['iso' => 'LB','name' => 'Lebanon','dialing_code' => '961'],
            ['iso' => 'LS','name' => 'Lesotho','dialing_code' => '266'],
            ['iso' => 'LR','name' => 'Liberia','dialing_code' => '231'],
            ['iso' => 'LY','name' => 'Libyan Arab Jamahiriya','dialing_code' => '218'],
            ['iso' => 'LI','name' => 'Liechtenstein','dialing_code' => '423'],
            ['iso' => 'LT','name' => 'Lithuania','dialing_code' => '370'],
            ['iso' => 'LU','name' => 'Luxembourg','dialing_code' => '352'],
            ['iso' => 'MO','name' => 'Macao','dialing_code' => '853'],
            ['iso' => 'MK','name' => 'Macedonia, the Former Yugoslav Republic of','dialing_code' => '389'],
            ['iso' => 'MG','name' => 'Madagascar','dialing_code' => '261'],
            ['iso' => 'MW','name' => 'Malawi','dialing_code' => '265'],
            ['iso' => 'MY','name' => 'Malaysia','dialing_code' => '60'],
            ['iso' => 'MV','name' => 'Maldives','dialing_code' => '960'],
            ['iso' => 'ML','name' => 'Mali','dialing_code' => '223'],
            ['iso' => 'MT','name' => 'Malta','dialing_code' => '356'],
            ['iso' => 'MH','name' => 'Marshall Islands','dialing_code' => '692'],
            ['iso' => 'MQ','name' => 'Martinique','dialing_code' => '596'],
            ['iso' => 'MR','name' => 'Mauritania','dialing_code' => '222'],
            ['iso' => 'MU','name' => 'Mauritius','dialing_code' => '230'],
            ['iso' => 'YT','name' => 'Mayotte','dialing_code' => '269'],
            ['iso' => 'MX','name' => 'Mexico','dialing_code' => '52'],
            ['iso' => 'FM','name' => 'Micronesia, Federated States of','dialing_code' => '691'],
            ['iso' => 'MD','name' => 'Moldova, Republic of','dialing_code' => '373'],
            ['iso' => 'MC','name' => 'Monaco','dialing_code' => '377'],
            ['iso' => 'MN','name' => 'Mongolia','dialing_code' => '976'],
            ['iso' => 'MS','name' => 'Montserrat','dialing_code' => '1664'],
            ['iso' => 'MA','name' => 'Morocco','dialing_code' => '212'],
            ['iso' => 'MZ','name' => 'Mozambique','dialing_code' => '258'],
            ['iso' => 'MM','name' => 'Myanmar','dialing_code' => '95'],
            ['iso' => 'NA','name' => 'Namibia','dialing_code' => '264'],
            ['iso' => 'NR','name' => 'Nauru','dialing_code' => '674'],
            ['iso' => 'NP','name' => 'Nepal','dialing_code' => '977'],
            ['iso' => 'NL','name' => 'Netherlands','dialing_code' => '31'],
            ['iso' => 'AN','name' => 'Netherlands Antilles','dialing_code' => '599'],
            ['iso' => 'NC','name' => 'New Caledonia','dialing_code' => '687'],
            ['iso' => 'NZ','name' => 'New Zealand','dialing_code' => '64'],
            ['iso' => 'NI','name' => 'Nicaragua','dialing_code' => '505'],
            ['iso' => 'NE','name' => 'Niger','dialing_code' => '227'],
            ['iso' => 'NG','name' => 'Nigeria','dialing_code' => '234'],
            ['iso' => 'NU','name' => 'Niue','dialing_code' => '683'],
            ['iso' => 'NF','name' => 'Norfolk Island','dialing_code' => '672'],
            ['iso' => 'MP','name' => 'Northern Mariana Islands','dialing_code' => '1670'],
            ['iso' => 'NO','name' => 'Norway','dialing_code' => '47'],
            ['iso' => 'OM','name' => 'Oman','dialing_code' => '968'],
            ['iso' => 'PK','name' => 'Pakistan','dialing_code' => '92'],
            ['iso' => 'PW','name' => 'Palau','dialing_code' => '680'],
            ['iso' => 'PS','name' => 'Palestinian Territory, Occupied','dialing_code' => '970'],
            ['iso' => 'PA','name' => 'Panama','dialing_code' => '507'],
            ['iso' => 'PG','name' => 'Papua New Guinea','dialing_code' => '675'],
            ['iso' => 'PY','name' => 'Paraguay','dialing_code' => '595'],
            ['iso' => 'PE','name' => 'Peru','dialing_code' => '51'],
            ['iso' => 'PH','name' => 'Philippines','dialing_code' => '63'],
            ['iso' => 'PN','name' => 'Pitcairn','dialing_code' => '0'],
            ['iso' => 'PL','name' => 'Poland','dialing_code' => '48'],
            ['iso' => 'PT','name' => 'Portugal','dialing_code' => '351'],
            ['iso' => 'PR','name' => 'Puerto Rico','dialing_code' => '1787'],
            ['iso' => 'QA','name' => 'Qatar','dialing_code' => '974'],
            ['iso' => 'RE','name' => 'Reunion','dialing_code' => '262'],
            ['iso' => 'RO','name' => 'Romania','dialing_code' => '40'],
            ['iso' => 'RU','name' => 'Russian Federation','dialing_code' => '70'],
            ['iso' => 'RW','name' => 'Rwanda','dialing_code' => '250'],
            ['iso' => 'SH','name' => 'Saint Helena','dialing_code' => '290'],
            ['iso' => 'KN','name' => 'Saint Kitts and Nevis','dialing_code' => '1869'],
            ['iso' => 'LC','name' => 'Saint Lucia','dialing_code' => '1758'],
            ['iso' => 'PM','name' => 'Saint Pierre and Miquelon','dialing_code' => '508'],
            ['iso' => 'VC','name' => 'Saint Vincent and the Grenadines','dialing_code' => '1784'],
            ['iso' => 'WS','name' => 'Samoa','dialing_code' => '684'],
            ['iso' => 'SM','name' => 'San Marino','dialing_code' => '378'],
            ['iso' => 'ST','name' => 'Sao Tome and Principe','dialing_code' => '239'],
            ['iso' => 'SA','name' => 'Saudi Arabia','dialing_code' => '966'],
            ['iso' => 'SN','name' => 'Senegal','dialing_code' => '221'],
            ['iso' => 'CS','name' => 'Serbia and Montenegro','dialing_code' => '381'],
            ['iso' => 'SC','name' => 'Seychelles','dialing_code' => '248'],
            ['iso' => 'SL','name' => 'Sierra Leone','dialing_code' => '232'],
            ['iso' => 'SG','name' => 'Singapore','dialing_code' => '65'],
            ['iso' => 'SK','name' => 'Slovakia','dialing_code' => '421'],
            ['iso' => 'SI','name' => 'Slovenia','dialing_code' => '386'],
            ['iso' => 'SB','name' => 'Solomon Islands','dialing_code' => '677'],
            ['iso' => 'SO','name' => 'Somalia','dialing_code' => '252'],
            ['iso' => 'ZA','name' => 'South Africa','dialing_code' => '27'],
            ['iso' => 'GS','name' => 'South Georgia and the South Sandwich Islands','dialing_code' => '0'],
            ['iso' => 'ES','name' => 'Spain','dialing_code' => '34'],
            ['iso' => 'LK','name' => 'Sri Lanka','dialing_code' => '94'],
            ['iso' => 'SD','name' => 'Sudan','dialing_code' => '249'],
            ['iso' => 'SR','name' => 'Suriname','dialing_code' => '597'],
            ['iso' => 'SJ','name' => 'Svalbard and Jan Mayen','dialing_code' => '47'],
            ['iso' => 'SZ','name' => 'Swaziland','dialing_code' => '268'],
            ['iso' => 'SE','name' => 'Sweden','dialing_code' => '46'],
            ['iso' => 'CH','name' => 'Switzerland','dialing_code' => '41'],
            ['iso' => 'SY','name' => 'Syrian Arab Republic','dialing_code' => '963'],
            ['iso' => 'TW','name' => 'Taiwan, Province of China','dialing_code' => '886'],
            ['iso' => 'TJ','name' => 'Tajikistan','dialing_code' => '992'],
            ['iso' => 'TZ','name' => 'Tanzania, United Republic of','dialing_code' => '255'],
            ['iso' => 'TH','name' => 'Thailand','dialing_code' => '66'],
            ['iso' => 'TL','name' => 'Timor-Leste','dialing_code' => '670'],
            ['iso' => 'TG','name' => 'Togo','dialing_code' => '228'],
            ['iso' => 'TK','name' => 'Tokelau','dialing_code' => '690'],
            ['iso' => 'TO','name' => 'Tonga','dialing_code' => '676'],
            ['iso' => 'TT','name' => 'Trinidad and Tobago','dialing_code' => '1868'],
            ['iso' => 'TN','name' => 'Tunisia','dialing_code' => '216'],
            ['iso' => 'TR','name' => 'Turkey','dialing_code' => '90'],
            ['iso' => 'TM','name' => 'Turkmenistan','dialing_code' => '7370'],
            ['iso' => 'TC','name' => 'Turks and Caicos Islands','dialing_code' => '1649'],
            ['iso' => 'TV','name' => 'Tuvalu','dialing_code' => '688'],
            ['iso' => 'UG','name' => 'Uganda','dialing_code' => '256'],
            ['iso' => 'UA','name' => 'Ukraine','dialing_code' => '380'],
            ['iso' => 'AE','name' => 'United Arab Emirates','dialing_code' => '971'],
            ['iso' => 'GB','name' => 'United Kingdom','dialing_code' => '44'],
            ['iso' => 'US','name' => 'United States','dialing_code' => '1'],
            ['iso' => 'UM','name' => 'United States Minor Outlying Islands','dialing_code' => '1'],
            ['iso' => 'UY','name' => 'Uruguay','dialing_code' => '598'],
            ['iso' => 'UZ','name' => 'Uzbekistan','dialing_code' => '998'],
            ['iso' => 'VU','name' => 'Vanuatu','dialing_code' => '678'],
            ['iso' => 'VE','name' => 'Venezuela','dialing_code' => '58'],
            ['iso' => 'VN','name' => 'Viet Nam','dialing_code' => '84'],
            ['iso' => 'VG','name' => 'Virgin Islands, British','dialing_code' => '1284'],
            ['iso' => 'VI','name' => 'Virgin Islands, U.s.','dialing_code' => '1340'],
            ['iso' => 'WF','name' => 'Wallis and Futuna','dialing_code' => '681'],
            ['iso' => 'EH','name' => 'Western Sahara','dialing_code' => '212'],
            ['iso' => 'YE','name' => 'Yemen','dialing_code' => '967'],
            ['iso' => 'ZM','name' => 'Zambia','dialing_code' => '260'],
            ['iso' => 'ZW','name' => 'Zimbabwe','dialing_code' => '263'],
            ['iso' => 'RS','name' => 'Serbia','dialing_code' => '381'],
            ['iso' => 'AP','name' => 'Asia / Pacific Region','dialing_code' => '0'],
            ['iso' => 'ME','name' => 'Montenegro','dialing_code' => '382'],
            ['iso' => 'AX','name' => 'Aland Islands','dialing_code' => '358'],
            ['iso' => 'BQ','name' => 'Bonaire, Sint Eustatius and Saba','dialing_code' => '599'],
            ['iso' => 'CW','name' => 'Curacao','dialing_code' => '599'],
            ['iso' => 'GG','name' => 'Guernsey','dialing_code' => '44'],
            ['iso' => 'IM','name' => 'Isle of Man','dialing_code' => '44'],
            ['iso' => 'JE','name' => 'Jersey','dialing_code' => '44'],
            ['iso' => 'XK','name' => 'Kosovo','dialing_code' => '381'],
            ['iso' => 'BL','name' => 'Saint Barthelemy','dialing_code' => '590'],
            ['iso' => 'MF','name' => 'Saint Martin','dialing_code' => '590'],
            ['iso' => 'SX','name' => 'Sint Maarten','dialing_code' => '1'],
            ['iso' => 'SS','name' => 'South Sudan','dialing_code' => '211']
        ];


        Country::insert($countries);
    }
}
